# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1207, 798)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 564))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self._1D = QtWidgets.QWidget()
        self._1D.setObjectName("_1D")
        self.gridLayout = QtWidgets.QGridLayout(self._1D)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self._1D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(250, 2000))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_1D = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_1D.sizePolicy().hasHeightForWidth())
        self.start_1D.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_1D.setFont(font)
        self.start_1D.setObjectName("start_1D")
        self.verticalLayout.addWidget(self.start_1D)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, -1)
        self.formLayout.setHorizontalSpacing(17)
        self.formLayout.setVerticalSpacing(7)
        self.formLayout.setObjectName("formLayout")
        self._1D_scan_settings = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._1D_scan_settings.sizePolicy().hasHeightForWidth())
        self._1D_scan_settings.setSizePolicy(sizePolicy)
        self._1D_scan_settings.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self._1D_scan_settings.setFont(font)
        self._1D_scan_settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._1D_scan_settings.setAlignment(QtCore.Qt.AlignCenter)
        self._1D_scan_settings.setWordWrap(False)
        self._1D_scan_settings.setObjectName("_1D_scan_settings")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self._1D_scan_settings)
        self._1D_gate_name_label = QtWidgets.QLabel(self.frame)
        self._1D_gate_name_label.setObjectName("_1D_gate_name_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self._1D_gate_name_label)
        self._1D_gate_name = QtWidgets.QComboBox(self.frame)
        self._1D_gate_name.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._1D_gate_name.sizePolicy().hasHeightForWidth())
        self._1D_gate_name.setSizePolicy(sizePolicy)
        self._1D_gate_name.setMinimumSize(QtCore.QSize(107, 0))
        self._1D_gate_name.setObjectName("_1D_gate_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self._1D_gate_name)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self._1D_V_swing = QtWidgets.QDoubleSpinBox(self.frame)
        self._1D_V_swing.setMinimumSize(QtCore.QSize(107, 0))
        self._1D_V_swing.setDecimals(1)
        self._1D_V_swing.setMinimum(-1500.0)
        self._1D_V_swing.setMaximum(1500.0)
        self._1D_V_swing.setObjectName("_1D_V_swing")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self._1D_V_swing)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self._1D_npt = QtWidgets.QSpinBox(self.frame)
        self._1D_npt.setMinimumSize(QtCore.QSize(107, 0))
        self._1D_npt.setMaximum(1000)
        self._1D_npt.setObjectName("_1D_npt")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self._1D_npt)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self._1D_t_meas = QtWidgets.QDoubleSpinBox(self.frame)
        self._1D_t_meas.setMinimumSize(QtCore.QSize(107, 0))
        self._1D_t_meas.setDecimals(1)
        self._1D_t_meas.setMaximum(100000.0)
        self._1D_t_meas.setObjectName("_1D_t_meas")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self._1D_t_meas)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self._1D_biasT_corr = QtWidgets.QCheckBox(self.frame)
        self._1D_biasT_corr.setText("")
        self._1D_biasT_corr.setObjectName("_1D_biasT_corr")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self._1D_biasT_corr)
        self._1D_update_plot = QtWidgets.QPushButton(self.frame)
        self._1D_update_plot.setObjectName("_1D_update_plot")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self._1D_update_plot)
        self.label_8 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setText("Scan Properties")
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.label_8)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self._1D_average = QtWidgets.QSpinBox(self.frame)
        self._1D_average.setObjectName("_1D_average")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self._1D_average)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self._1D_diff = QtWidgets.QCheckBox(self.frame)
        self._1D_diff.setText("")
        self._1D_diff.setObjectName("_1D_diff")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self._1D_diff)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self._1D_ppt_save = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._1D_ppt_save.sizePolicy().hasHeightForWidth())
        self._1D_ppt_save.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self._1D_ppt_save.setFont(font)
        self._1D_ppt_save.setObjectName("_1D_ppt_save")
        self.verticalLayout.addWidget(self._1D_ppt_save)
        spacerItem1 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self._1D_save_data = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._1D_save_data.sizePolicy().hasHeightForWidth())
        self._1D_save_data.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self._1D_save_data.setFont(font)
        self._1D_save_data.setObjectName("_1D_save_data")
        self.verticalLayout.addWidget(self._1D_save_data)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self._1D_plotter_frame = QtWidgets.QFrame(self._1D)
        self._1D_plotter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._1D_plotter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._1D_plotter_frame.setObjectName("_1D_plotter_frame")
        self._1D_plotter_layout = QtWidgets.QGridLayout(self._1D_plotter_frame)
        self._1D_plotter_layout.setObjectName("_1D_plotter_layout")
        self.gridLayout.addWidget(self._1D_plotter_frame, 0, 2, 1, 1)
        self.tabWidget.addTab(self._1D, "")
        self._1D_MOD = QtWidgets.QWidget()
        self._1D_MOD.setObjectName("_1D_MOD")
        self.gridLayout_2 = QtWidgets.QGridLayout(self._1D_MOD)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_5 = QtWidgets.QFrame(self._1D_MOD)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5.addWidget(self.frame_5, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self._1D_MOD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(250, 2000))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.start_1D_2 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_1D_2.sizePolicy().hasHeightForWidth())
        self.start_1D_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_1D_2.setFont(font)
        self.start_1D_2.setObjectName("start_1D_2")
        self.verticalLayout_2.addWidget(self.start_1D_2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(0, 0, 0, -1)
        self.formLayout_2.setHorizontalSpacing(17)
        self.formLayout_2.setVerticalSpacing(7)
        self.formLayout_2.setObjectName("formLayout_2")
        self._1D_scan_settings_2 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._1D_scan_settings_2.sizePolicy().hasHeightForWidth())
        self._1D_scan_settings_2.setSizePolicy(sizePolicy)
        self._1D_scan_settings_2.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self._1D_scan_settings_2.setFont(font)
        self._1D_scan_settings_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._1D_scan_settings_2.setAlignment(QtCore.Qt.AlignCenter)
        self._1D_scan_settings_2.setWordWrap(False)
        self._1D_scan_settings_2.setObjectName("_1D_scan_settings_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self._1D_scan_settings_2)
        self._1D_gate_name_label_2 = QtWidgets.QLabel(self.frame_2)
        self._1D_gate_name_label_2.setObjectName("_1D_gate_name_label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self._1D_gate_name_label_2)
        self._1D_gate_name_2 = QtWidgets.QComboBox(self.frame_2)
        self._1D_gate_name_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._1D_gate_name_2.sizePolicy().hasHeightForWidth())
        self._1D_gate_name_2.setSizePolicy(sizePolicy)
        self._1D_gate_name_2.setMinimumSize(QtCore.QSize(107, 0))
        self._1D_gate_name_2.setObjectName("_1D_gate_name_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self._1D_gate_name_2)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self._1D_V_swing_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self._1D_V_swing_2.setMinimumSize(QtCore.QSize(107, 0))
        self._1D_V_swing_2.setDecimals(1)
        self._1D_V_swing_2.setMinimum(-1500.0)
        self._1D_V_swing_2.setMaximum(1500.0)
        self._1D_V_swing_2.setSingleStep(100.0)
        self._1D_V_swing_2.setObjectName("_1D_V_swing_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self._1D_V_swing_2)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self._1D_npt_2 = QtWidgets.QSpinBox(self.frame_2)
        self._1D_npt_2.setMinimumSize(QtCore.QSize(107, 0))
        self._1D_npt_2.setMaximum(1000)
        self._1D_npt_2.setSingleStep(100)
        self._1D_npt_2.setObjectName("_1D_npt_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self._1D_npt_2)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self._1D_t_meas_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self._1D_t_meas_2.setMinimumSize(QtCore.QSize(107, 0))
        self._1D_t_meas_2.setDecimals(1)
        self._1D_t_meas_2.setMaximum(100000.0)
        self._1D_t_meas_2.setSingleStep(100.0)
        self._1D_t_meas_2.setObjectName("_1D_t_meas_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self._1D_t_meas_2)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self._1D_biasT_corr_2 = QtWidgets.QCheckBox(self.frame_2)
        self._1D_biasT_corr_2.setText("")
        self._1D_biasT_corr_2.setObjectName("_1D_biasT_corr_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self._1D_biasT_corr_2)
        self.update_plot_2 = QtWidgets.QPushButton(self.frame_2)
        self.update_plot_2.setObjectName("update_plot_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.update_plot_2)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_13.setText("Scan Properties")
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setScaledContents(False)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self._1D_average_2 = QtWidgets.QSpinBox(self.frame_2)
        self._1D_average_2.setObjectName("_1D_average_2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self._1D_average_2)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self._1D_diff_2 = QtWidgets.QCheckBox(self.frame_2)
        self._1D_diff_2.setText("")
        self._1D_diff_2.setObjectName("_1D_diff_2")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self._1D_diff_2)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self._1Dm_ppt_save = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._1Dm_ppt_save.sizePolicy().hasHeightForWidth())
        self._1Dm_ppt_save.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self._1Dm_ppt_save.setFont(font)
        self._1Dm_ppt_save.setObjectName("_1Dm_ppt_save")
        self.verticalLayout_2.addWidget(self._1Dm_ppt_save)
        spacerItem3 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self._1Dm_save_data = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._1Dm_save_data.sizePolicy().hasHeightForWidth())
        self._1Dm_save_data.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self._1Dm_save_data.setFont(font)
        self._1Dm_save_data.setObjectName("_1Dm_save_data")
        self.verticalLayout_2.addWidget(self._1Dm_save_data)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self._1D_MOD, "")
        self._2D = QtWidgets.QWidget()
        self._2D.setObjectName("_2D")
        self.gridLayout_9 = QtWidgets.QGridLayout(self._2D)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_3 = QtWidgets.QFrame(self._2D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMaximumSize(QtCore.QSize(250, 2000))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.start_2D = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_2D.sizePolicy().hasHeightForWidth())
        self.start_2D.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_2D.setFont(font)
        self.start_2D.setObjectName("start_2D")
        self.verticalLayout_3.addWidget(self.start_2D)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setContentsMargins(0, 0, 0, -1)
        self.formLayout_3.setHorizontalSpacing(17)
        self.formLayout_3.setVerticalSpacing(7)
        self.formLayout_3.setObjectName("formLayout_3")
        self._1D_scan_settings_3 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._1D_scan_settings_3.sizePolicy().hasHeightForWidth())
        self._1D_scan_settings_3.setSizePolicy(sizePolicy)
        self._1D_scan_settings_3.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self._1D_scan_settings_3.setFont(font)
        self._1D_scan_settings_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._1D_scan_settings_3.setAlignment(QtCore.Qt.AlignCenter)
        self._1D_scan_settings_3.setWordWrap(False)
        self._1D_scan_settings_3.setObjectName("_1D_scan_settings_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self._1D_scan_settings_3)
        self._1D_gate_name_label_3 = QtWidgets.QLabel(self.frame_3)
        self._1D_gate_name_label_3.setObjectName("_1D_gate_name_label_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self._1D_gate_name_label_3)
        self._2D_gate1_name = QtWidgets.QComboBox(self.frame_3)
        self._2D_gate1_name.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._2D_gate1_name.sizePolicy().hasHeightForWidth())
        self._2D_gate1_name.setSizePolicy(sizePolicy)
        self._2D_gate1_name.setMinimumSize(QtCore.QSize(107, 0))
        self._2D_gate1_name.setObjectName("_2D_gate1_name")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self._2D_gate1_name)
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self._2D_V1_swing = QtWidgets.QDoubleSpinBox(self.frame_3)
        self._2D_V1_swing.setMinimumSize(QtCore.QSize(107, 0))
        self._2D_V1_swing.setDecimals(2)
        self._2D_V1_swing.setMinimum(-3000.0)
        self._2D_V1_swing.setMaximum(3000.0)
        self._2D_V1_swing.setProperty("value", 0.0)
        self._2D_V1_swing.setObjectName("_2D_V1_swing")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self._2D_V1_swing)
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setObjectName("label_24")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self._2D_gate2_name = QtWidgets.QComboBox(self.frame_3)
        self._2D_gate2_name.setObjectName("_2D_gate2_name")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self._2D_gate2_name)
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setObjectName("label_25")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self._2D_V2_swing = QtWidgets.QDoubleSpinBox(self.frame_3)
        self._2D_V2_swing.setMinimum(-3000.0)
        self._2D_V2_swing.setMaximum(3000.0)
        self._2D_V2_swing.setObjectName("_2D_V2_swing")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self._2D_V2_swing)
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self._2D_npt = QtWidgets.QSpinBox(self.frame_3)
        self._2D_npt.setMinimumSize(QtCore.QSize(107, 0))
        self._2D_npt.setMinimum(0)
        self._2D_npt.setMaximum(1000)
        self._2D_npt.setObjectName("_2D_npt")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self._2D_npt)
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setObjectName("label_19")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self._2D_t_meas = QtWidgets.QDoubleSpinBox(self.frame_3)
        self._2D_t_meas.setMinimumSize(QtCore.QSize(107, 0))
        self._2D_t_meas.setDecimals(1)
        self._2D_t_meas.setMaximum(100000.0)
        self._2D_t_meas.setObjectName("_2D_t_meas")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self._2D_t_meas)
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self._2D_biasT_corr = QtWidgets.QCheckBox(self.frame_3)
        self._2D_biasT_corr.setText("")
        self._2D_biasT_corr.setObjectName("_2D_biasT_corr")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self._2D_biasT_corr)
        self._2D_update_plot = QtWidgets.QPushButton(self.frame_3)
        self._2D_update_plot.setObjectName("_2D_update_plot")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self._2D_update_plot)
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_20.setText("Scan Properties")
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setScaledContents(False)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.frame_3)
        self.label_21.setObjectName("label_21")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self._2D_average = QtWidgets.QSpinBox(self.frame_3)
        self._2D_average.setMaximum(500)
        self._2D_average.setObjectName("_2D_average")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self._2D_average)
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self._2D_diff = QtWidgets.QCheckBox(self.frame_3)
        self._2D_diff.setText("")
        self._2D_diff.setObjectName("_2D_diff")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.FieldRole, self._2D_diff)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self._2D_ppt_save = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._2D_ppt_save.sizePolicy().hasHeightForWidth())
        self._2D_ppt_save.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self._2D_ppt_save.setFont(font)
        self._2D_ppt_save.setObjectName("_2D_ppt_save")
        self.verticalLayout_3.addWidget(self._2D_ppt_save)
        spacerItem5 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem5)
        self._2D_save_data = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._2D_save_data.sizePolicy().hasHeightForWidth())
        self._2D_save_data.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self._2D_save_data.setFont(font)
        self._2D_save_data.setObjectName("_2D_save_data")
        self.verticalLayout_3.addWidget(self._2D_save_data)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_3, 0, 0, 1, 1)
        self._2D_plotter_frame = QtWidgets.QFrame(self._2D)
        self._2D_plotter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._2D_plotter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self._2D_plotter_frame.setObjectName("_2D_plotter_frame")
        self._2D_plotter_layout = QtWidgets.QGridLayout(self._2D_plotter_frame)
        self._2D_plotter_layout.setObjectName("_2D_plotter_layout")
        self.gridLayout_9.addWidget(self._2D_plotter_frame, 0, 1, 1, 1)
        self.tabWidget.addTab(self._2D, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 10, 221, 131))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 201, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self._1D_scan_settings_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._1D_scan_settings_4.sizePolicy().hasHeightForWidth())
        self._1D_scan_settings_4.setSizePolicy(sizePolicy)
        self._1D_scan_settings_4.setMinimumSize(QtCore.QSize(0, 24))
        self._1D_scan_settings_4.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self._1D_scan_settings_4.setFont(font)
        self._1D_scan_settings_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self._1D_scan_settings_4.setAlignment(QtCore.Qt.AlignCenter)
        self._1D_scan_settings_4.setWordWrap(False)
        self._1D_scan_settings_4.setObjectName("_1D_scan_settings_4")
        self.verticalLayout_4.addWidget(self._1D_scan_settings_4)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setHorizontalSpacing(6)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self._ch1 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self._ch1.setText("")
        self._ch1.setChecked(True)
        self._ch1.setObjectName("_ch1")
        self.horizontalLayout_8.addWidget(self._ch1, 0, QtCore.Qt.AlignHCenter)
        self._ch2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self._ch2.setText("")
        self._ch2.setChecked(True)
        self._ch2.setObjectName("_ch2")
        self.horizontalLayout_8.addWidget(self._ch2, 0, QtCore.Qt.AlignHCenter)
        self._ch3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self._ch3.setText("")
        self._ch3.setChecked(True)
        self._ch3.setObjectName("_ch3")
        self.horizontalLayout_8.addWidget(self._ch3, 0, QtCore.Qt.AlignHCenter)
        self._ch4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self._ch4.setText("")
        self._ch4.setChecked(True)
        self._ch4.setObjectName("_ch4")
        self.horizontalLayout_8.addWidget(self._ch4, 0, QtCore.Qt.AlignHCenter)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_43 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_48 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_10.addWidget(self.label_48, 0, QtCore.Qt.AlignHCenter)
        self.label_49 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_10.addWidget(self.label_49, 0, QtCore.Qt.AlignHCenter)
        self.label_50 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_10.addWidget(self.label_50, 0, QtCore.Qt.AlignHCenter)
        self.label_51 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_10.addWidget(self.label_51, 0, QtCore.Qt.AlignHCenter)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.label_52 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_52.setObjectName("label_52")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_52)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._sample_rate = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self._sample_rate.setEditable(False)
        self._sample_rate.setObjectName("_sample_rate")
        self._sample_rate.addItem("")
        self._sample_rate.addItem("")
        self.horizontalLayout.addWidget(self._sample_rate)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.formLayout_4)
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(230, 90, 191, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(230, 110, 191, 16))
        self.label_27.setObjectName("label_27")
        self.label_27.raise_()
        self.frame_4.raise_()
        self.label_26.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1207, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_1D.setText(_translate("MainWindow", "Start"))
        self._1D_scan_settings.setText(_translate("MainWindow", "Scan Settings"))
        self._1D_gate_name_label.setText(_translate("MainWindow", "Gate"))
        self.label_5.setText(_translate("MainWindow", "V Swing  (mV)"))
        self.label_2.setText(_translate("MainWindow", "N pt"))
        self.label.setText(_translate("MainWindow", "T meas (us)"))
        self.label_4.setText(_translate("MainWindow", "Bias T corr"))
        self._1D_update_plot.setText(_translate("MainWindow", "Upload waveform"))
        self.label_3.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Average"))
        self.label_7.setText(_translate("MainWindow", "Differentiate"))
        self._1D_ppt_save.setText(_translate("MainWindow", "Copy to PPT"))
        self._1D_save_data.setText(_translate("MainWindow", "Save Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self._1D), _translate("MainWindow", "1D"))
        self.start_1D_2.setText(_translate("MainWindow", "Start"))
        self._1D_scan_settings_2.setText(_translate("MainWindow", "Scan Settings"))
        self._1D_gate_name_label_2.setText(_translate("MainWindow", "Gate"))
        self.label_10.setText(_translate("MainWindow", "V Swing  (mV)"))
        self.label_11.setText(_translate("MainWindow", "N pt"))
        self.label_12.setText(_translate("MainWindow", "T meas (us)"))
        self.label_15.setText(_translate("MainWindow", "Bias T corr"))
        self.update_plot_2.setText(_translate("MainWindow", "Upload waveform"))
        self.label_14.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "Average"))
        self.label_16.setText(_translate("MainWindow", "Differentiate"))
        self._1Dm_ppt_save.setText(_translate("MainWindow", "Copy to PPT"))
        self._1Dm_save_data.setText(_translate("MainWindow", "Save Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self._1D_MOD), _translate("MainWindow", "1D modulated"))
        self.start_2D.setText(_translate("MainWindow", "Start"))
        self._1D_scan_settings_3.setText(_translate("MainWindow", "Scan Settings"))
        self._1D_gate_name_label_3.setText(_translate("MainWindow", "x-axis"))
        self.label_17.setText(_translate("MainWindow", "V Swing x (mV)"))
        self.label_24.setText(_translate("MainWindow", "y-axis"))
        self.label_25.setText(_translate("MainWindow", "V Swing y (mV)"))
        self.label_18.setText(_translate("MainWindow", "N pt"))
        self.label_19.setText(_translate("MainWindow", "T meas (us)"))
        self.label_22.setText(_translate("MainWindow", "Bias T corr"))
        self._2D_update_plot.setText(_translate("MainWindow", "Upload waveform"))
        self.label_21.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "Average"))
        self.label_23.setText(_translate("MainWindow", "Differentiate"))
        self._2D_ppt_save.setText(_translate("MainWindow", "Copy to PPT"))
        self._2D_save_data.setText(_translate("MainWindow", "Save Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self._2D), _translate("MainWindow", "2D"))
        self._1D_scan_settings_4.setText(_translate("MainWindow", "General settings"))
        self.label_9.setText(_translate("MainWindow", "Scan channel"))
        self.label_48.setText(_translate("MainWindow", "Ch1"))
        self.label_49.setText(_translate("MainWindow", "Ch2"))
        self.label_50.setText(_translate("MainWindow", "Ch3"))
        self.label_51.setText(_translate("MainWindow", "Ch4"))
        self.label_52.setText(_translate("MainWindow", "Sample rate"))
        self._sample_rate.setItemText(0, _translate("MainWindow", "100"))
        self._sample_rate.setItemText(1, _translate("MainWindow", "500"))
        self.label_6.setText(_translate("MainWindow", "MS"))
        self.label_26.setText(_translate("MainWindow", "Currently, there is a bug with Keysight"))
        self.label_27.setText(_translate("MainWindow", "only allowing 100 and 500 MS."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Settings"))

