# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'script_runner_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.centralLayout.setObjectName("centralLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollLayout = QtWidgets.QGridLayout(self.scrollArea)
        self.scrollLayout.setObjectName("scrollLayout")
        self.commands_widget = QtWidgets.QWidget()
        self.commands_widget.setObjectName("commands_widget")
        self.commands_layout = QtWidgets.QGridLayout(self.commands_widget)
        self.commands_layout.setSpacing(2)
        self.commands_layout.setObjectName("commands_layout")
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.commands_layout.addItem(spacerItem, 100, 0, 1, 20)
        self.scrollLayout.addWidget(self.commands_widget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.commands_widget)
        self.centralLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Script Runner"))
