# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_browser_v2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dataviewer(object):
    def setupUi(self, dataviewer):
        dataviewer.setObjectName("dataviewer")
        dataviewer.resize(1141, 631)
        self.centralwidget = QtWidgets.QWidget(dataviewer)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setOpaqueResize(True)
        self.splitter_2.setObjectName("splitter_2")
        self.toppart = QtWidgets.QWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toppart.sizePolicy().hasHeightForWidth())
        self.toppart.setSizePolicy(sizePolicy)
        self.toppart.setObjectName("toppart")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.toppart)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.topbar = QtWidgets.QWidget(self.toppart)
        self.topbar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topbar.sizePolicy().hasHeightForWidth())
        self.topbar.setSizePolicy(sizePolicy)
        self.topbar.setMinimumSize(QtCore.QSize(0, 0))
        self.topbar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.topbar.setObjectName("topbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topbar)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logfile = QtWidgets.QLabel(self.topbar)
        self.logfile.setObjectName("logfile")
        self.horizontalLayout.addWidget(self.logfile)
        spacerItem = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.filter_button = QtWidgets.QPushButton(self.topbar)
        self.filter_button.setObjectName("filter_button")
        self.horizontalLayout.addWidget(self.filter_button)
        spacerItem1 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.filter_input = QtWidgets.QLineEdit(self.topbar)
        self.filter_input.setObjectName("filter_input")
        self.horizontalLayout.addWidget(self.filter_input)
        self.verticalLayout.addWidget(self.topbar)
        self.splitter = QtWidgets.QSplitter(self.toppart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.data_view = QtWidgets.QTreeView(self.splitter)
        self.data_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.data_view.setObjectName("data_view")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.bottompart = QtWidgets.QWidget(self.splitter_2)
        self.bottompart.setObjectName("bottompart")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.bottompart)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.data_select_lay = QtWidgets.QFormLayout()
        self.data_select_lay.setObjectName("data_select_lay")
        self.horizontalLayout_4.addLayout(self.data_select_lay)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bottombar = QtWidgets.QWidget(self.bottompart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottombar.sizePolicy().hasHeightForWidth())
        self.bottombar.setSizePolicy(sizePolicy)
        self.bottombar.setMinimumSize(QtCore.QSize(0, 0))
        self.bottombar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bottombar.setObjectName("bottombar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.bottombar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.send_ppt = QtWidgets.QPushButton(self.bottombar)
        self.send_ppt.setObjectName("send_ppt")
        self.horizontalLayout_3.addWidget(self.send_ppt)
        spacerItem3 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.copy_im = QtWidgets.QPushButton(self.bottombar)
        self.copy_im.setObjectName("copy_im")
        self.horizontalLayout_3.addWidget(self.copy_im)
        spacerItem4 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.split_data = QtWidgets.QPushButton(self.bottombar)
        self.split_data.setObjectName("split_data")
        self.horizontalLayout_3.addWidget(self.split_data)
        self.verticalLayout_2.addWidget(self.bottombar)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        dataviewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dataviewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1141, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Data = QtWidgets.QMenu(self.menubar)
        self.menu_Data.setObjectName("menu_Data")
        self.menuFolder = QtWidgets.QMenu(self.menubar)
        self.menuFolder.setObjectName("menuFolder")
        dataviewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dataviewer)
        self.statusbar.setObjectName("statusbar")
        dataviewer.setStatusBar(self.statusbar)
        self.actionReload_data = QtWidgets.QAction(dataviewer)
        self.actionReload_data.setObjectName("actionReload_data")
        self.actionPreload_all_info = QtWidgets.QAction(dataviewer)
        self.actionPreload_all_info.setObjectName("actionPreload_all_info")
        self.actionQui = QtWidgets.QAction(dataviewer)
        self.actionQui.setObjectName("actionQui")
        self.actionAdd_directory = QtWidgets.QAction(dataviewer)
        self.actionAdd_directory.setObjectName("actionAdd_directory")
        self.menu_Data.addAction(self.actionReload_data)
        self.menu_Data.addAction(self.actionPreload_all_info)
        self.menu_Data.addAction(self.actionQui)
        self.menuFolder.addAction(self.actionAdd_directory)
        self.menubar.addAction(self.menu_Data.menuAction())
        self.menubar.addAction(self.menuFolder.menuAction())

        self.retranslateUi(dataviewer)
        QtCore.QMetaObject.connectSlotsByName(dataviewer)

    def retranslateUi(self, dataviewer):
        _translate = QtCore.QCoreApplication.translate
        dataviewer.setWindowTitle(_translate("dataviewer", "dataviewer"))
        self.logfile.setText(_translate("dataviewer", "V2"))
        self.filter_button.setText(_translate("dataviewer", "Filter data"))
        self.send_ppt.setText(_translate("dataviewer", "Send data to powerpoint"))
        self.copy_im.setText(_translate("dataviewer", "Copy image to clipboard"))
        self.split_data.setText(_translate("dataviewer", "Split dataset"))
        self.menu_Data.setTitle(_translate("dataviewer", "&Data"))
        self.menuFolder.setTitle(_translate("dataviewer", "Folder"))
        self.actionReload_data.setText(_translate("dataviewer", "Reload data"))
        self.actionPreload_all_info.setText(_translate("dataviewer", "Preload all info"))
        self.actionQui.setText(_translate("dataviewer", "Quit"))
        self.actionAdd_directory.setText(_translate("dataviewer", "Add directory"))

